// swift-tools-version:5.9
// Generated by SwiftFlowKit

import PackageDescription

let package = Package(
    name: "SwiftPicker",
    platforms: [
        .macOS(.v10_14),
    ],
    products: [
        .library(
            name: "SwiftPicker",
            targets: ["SwiftPicker"]
        ),
        .executable(
            name: "SwiftPickerExecutable",
            targets: ["SwiftPickerExecutable"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/nikolainobadi/ANSITerminalModified", from: "0.6.0")
    ],
    targets: [
        .target(
            name: "SwiftPicker",
            dependencies: [
                .product(name: "ANSITerminal", package: "ANSITerminalModified")
            ]
        ),
        .testTarget(
            name: "SwiftPickerTests",
            dependencies: ["SwiftPicker"]
        ),
        .executableTarget(
            name: "SwiftPickerExecutable",
            dependencies: ["SwiftPicker"]
        ),
    ]
)
