// swift-tools-version:5.9
// Generated by SwiftFlowKit

import PackageDescription

let package = Package(
    name: "SwiftPicker",
    products: [
        .library(
            name: "SwiftPicker",
            targets: ["SwiftPicker"]
        ),
        .executable(
            name: "SwiftPickerExecutable",
            targets: ["SwiftPickerExecutable"]
        ),
    ],
    dependencies: [
    ],
    targets: [
        .target(
            name: "SwiftPicker",
            dependencies: [
            ]
        ),
        .executableTarget(
            name: "SwiftPickerExecutable",
            dependencies: ["SwiftPicker"]
        ),
    ]
)
